FROM edasque/qmk_firmware
MAINTAINER Yoshi Yamaguchi ymotongpoo

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
&& apt-get install -y curl \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

